server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: first
#          uri: http://localhost:8081
#          predicates:
#            - Path=/first-service/**
#        - id: second
#          uri: http://localhost:8082
#          predicates:
#            - Path=/second-service/**