server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first
          uri: http://localhost:8081
          predicates:
            - Path=/first-service/**
        - id: second
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/**